
create table if not exists users (
 id bigint generated by default as identity primary key,
 login text unique not null,
 password text not null,
 nickname text,
 role text default 'USER',
 confirmed boolean default false
);

create table if not exists players (
 id bigint generated by default as identity primary key,
 nickname text not null,
 avatar text default '',
 role text default '',
 kd text default '',
 description text default ''
);

create table if not exists news (
 id bigint generated by default as identity primary key,
 title text,
 body text
);
