-- Firezone users and roles

create table if not exists profiles (
 id uuid primary key,
 nickname text unique not null,
 role text default 'USER',
 confirmed boolean default false
);

create table if not exists players (
 id bigint generated by default as identity primary key,
 nickname text not null,
 avatar text default '',
 role text default '',
 kd text default '',
 description text default ''
);

create table if not exists news (
 id bigint generated by default as identity primary key,
 title text,
 body text,
 image text default ''
);

create table if not exists matches (
 id bigint generated by default as identity primary key,
 enemy text,
 score text,
 result text
);
